package com.example.diffviewer.retrofit.model

data class PullRequestResponse(
    val author_association: String,
    val body: String,
    val closed_at: String,
    val comments_url: String,
    val created_at: String,
    val diff_url: String,
    val commits_url: String,
    val draft: String,
    val html_url: String,
    val issue_url: String,
    val merge_commit_sha: String,
    val merged_at: String,
    val node_id: String,
    val locked: Boolean,
    val patch_url: String,
    val review_comment_url: String,
    val review_comments_url: String,
    val state: String,
    val statuses_url: String,
    val title: String,
    val updated_at: String,
    val url: String,
    val fork: Boolean,
    val number: Int,
    val id: Int,
    val user: User
)

data class User(
    val avatar_url: String,
    val events_url: String,
    val followers_url: String,
    val following_url: String,
    val gists_url: String,
    val gravatar_id: String,
    val html_url: String,
    val id: Int,
    val login: String,
    val node_id: String,
    val organizations_url: String,
    val received_events_url: String,
    val repos_url: String,
    val site_admin: Boolean,
    val starred_url: String,
    val subscriptions_url: String,
    val type: String,
    val url: String
)